apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: observe-k8s-wg
  region: eu-west-1
  version: "1.22"
iam:
  withOIDC: true
managedNodeGroups:
- name: default-ng
  minSize: 1
  maxSize: 5
  desiredCapacity: 3
  labels: {role: mngworker}
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      ebs: true
      albIngress: true
      xRay: true
      cloudWatch: true
      appMesh: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
